RM url path
ONSdigital/sdc-responses-dashboard-react pull request #19
Opened 2018-06-07 09:07 UTC by SamGodwin2

### What is the context of this PR?
Changed the url for the RM service and updated the readme

### How to review 
New url is correct

2018-06-07 09:09 UTC, AdamHawtin requested changes

2018-06-07 09:09 UTC, AdamHawtin commented on README.md
> +`REACT_APP_UUID` refers to the unique identifyer RM uses to identify each excercise. This variable has no default and must be provided on app startup.
Can we rename this to something more specific like `REACT_APP_COLLECTION_EXERCISE_ID`?

2018-06-07 09:17 UTC, MebinAbraham commented on README.md
> +`REACT_APP_UUID` refers to the unique identifyer RM uses to identify each excercise. This variable has no default and must be provided on app startup.
Why does it need to be prefixed with `REACT_APP`, is that a bp?

2018-06-07 09:41 UTC, SamGodwin2 commented on README.md
> +`REACT_APP_UUID` refers to the unique identifyer RM uses to identify each excercise. This variable has no default and must be provided on app startup.
Its a security  thing all react envs have to be prefixed with `REACT_APP` helps prevent private envs from being exposed.

2018-06-07 10:16 UTC, MebinAbraham commented on README.md
> +`REACT_APP_UUID` refers to the unique identifyer RM uses to identify each excercise. This variable has no default and must be provided on app startup.
Just change the UUID bit as a lot of things are UUID's, explicitly stating makes it clearer. 👍

2018-06-08 07:43 UTC, AdamHawtin approved these changes

2018-06-08 07:58 UTC, merged